import { useMemo, useState } from 'react';
import SpatialView from '../spatial/SpatialView';
import Companion from '../components/Companion';
import { DEFAULT_PROFILE, SYNTHETIC_SCENE, BENCH_CLEAR_POSITION } from '../spatial/fixtures';
import { appendOperation, applyScenario, createScenario, undoScenario } from '../spatial/scenario';
import { solveScene } from '../spatial/solver';
import {contentHash} from '../spatial/validation';
import type { Operation, Profile, Project } from '../spatial/contracts';
import { confirmTargets, createPlan, serializePlan, type Confirmation, type ImprovementPlan, type Origin } from '../plans';
import './workspace.css';
export type WorkspaceProps={initialPlan?:ImprovementPlan;initialProject?:Project;onHome:()=>void;onSave:(plan:ImprovementPlan)=>void};
export default function Workspace({initialPlan,initialProject,onHome,onSave}:WorkspaceProps) {
  const initial=initialPlan?.project??initialProject;
  const [scene]=useState(()=>structuredClone(initial?.scene??SYNTHETIC_SCENE));
  const [profile,setProfile]=useState(()=>structuredClone(initial?.profile??DEFAULT_PROFILE));
  const [scenario,setScenario]=useState(()=>structuredClone(initial?.scenario??createScenario(scene,profile)));
  const [view,setView]=useState<'map'|'3d'|'split'>('3d');const [comparison,setComparison]=useState<'original'|'proposed'>('proposed');
  const [selected,setSelected]=useState<string|null>('bench');const [target,setTarget]=useState(initialPlan?.confirmation.targets[0]?.id??'bench');
  const [mode,setMode]=useState<'concern'|'proactive'>(initialPlan?.origin.kind??'proactive');
  const [message,setMessage]=useState(initialPlan?.origin.kind==='concern'?initialPlan.origin.originalText:'');
  const [language,setLanguage]=useState(initialPlan?.origin.kind==='concern'?initialPlan.origin.language:'en');
  const [interpretation,setInterpretation]=useState(initialPlan?.confirmation.interpretation??'');
  const [confirmation,setConfirmation]=useState<Confirmation|null>(initialPlan?.confirmation??null);const [origin,setOrigin]=useState<Origin|null>(initialPlan?.origin??null);
  const [savedIdentity,setSavedIdentity]=useState(initialPlan?{id:initialPlan.id,createdAt:initialPlan.createdAt,originHash:contentHash(initialPlan.origin)}:null);
  const [title,setTitle]=useState(initialPlan?.title??'Review the visitor approach');const [decision,setDecision]=useState<ImprovementPlan['decision']>(initialPlan?.decision??'planned');const [notes,setNotes]=useState(initialPlan?.notes??'');
  const [error,setError]=useState('');const [status,setStatus]=useState(initialPlan?'Saved plan reopened. The comparison has been recalculated.':'');const [plan,setPlan]=useState<ImprovementPlan|null>(initialPlan??null);
  const [move,setMove]=useState({x:BENCH_CLEAR_POSITION.x.toString(),y:BENCH_CLEAR_POSITION.y.toString()});
  const baseline=useMemo(()=>solveScene(scene,profile),[scene,profile]);const proposed=useMemo(()=>solveScene(scene,profile,scenario),[scene,profile,scenario]);const applied=useMemo(()=>applyScenario(scene,profile,scenario),[scene,profile,scenario]);
  const displayed=comparison==='original'?scene:applied;const result=comparison==='original'?baseline:proposed;
  const inventory=[...scene.obstacles,...scene.supports,...scene.unknown];const feature=scene.obstacles.find(o=>o.id===target);
  const editable=!!confirmation?.targets.some(t=>t.id===target)&&!!feature?.movable&&!!feature.reviewed;
  const dirty=()=>{setPlan(null);setStatus('Unsaved changes');};
  function resetReview(){setConfirmation(null);setOrigin(null);setScenario(createScenario(scene,profile));dirty();}
  function confirm(){try{
    if(mode==='concern'&&!message.trim())throw new Error('Enter the visitor concern, or choose a proactive check.');
    if(!interpretation.trim())throw new Error('Describe the issue you confirmed against the evidence.');
    const id=crypto.randomUUID();
    const next:Origin=mode==='concern'?{kind:'concern',id,source:{id:`report-${id}`,revision:'1',description:'Operator-entered visitor report; retained only on this device.',provenance:'local',permission:'local-only'},originalText:message,language,supportingSpan:{start:0,end:message.length,quote:message}}:{kind:'proactive',id,source:{id:'authored-courtyard-check',revision:String(scene.revision),description:'Operator check of the authored synthetic courtyard.',provenance:'synthetic',permission:'exportable'},expectation:`Review modeled access from the start to ${scene.destinations[0]?.label??'the destination'} under explicit movement requirements.`,method:'Deterministic horizontal square-envelope check; operator reviews linked evidence.'};
    const checked=confirmTargets({origin:next,scene,targetIds:[target],reviewer:'Local operator',interpretation:interpretation.trim()});setOrigin(next);setConfirmation(checked);setScenario(createScenario(scene,profile));setSelected(target);setError('');dirty();setStatus('Feature confirmed. Review a supported change below.');
  }catch(e){setError((e as Error).message);}}
  function edit(operation:Operation){try{if(!editable)throw new Error('Confirm this movable feature before editing.');setScenario(appendOperation(scene,profile,scenario,operation));setComparison('proposed');setError('');dirty();}catch(e){setError((e as Error).message);}}
  function changeProfile(next:Profile){try{solveScene(scene,next);setProfile(next);setScenario(createScenario(scene,next));setComparison('proposed');setError('');dirty();}catch(e){setError((e as Error).message);}}
  function save(){try{if(!origin||!confirmation)throw new Error('Confirm an issue and its feature before saving a plan.');const same=savedIdentity?.originHash===contentHash(origin);const next=createPlan({id:same?savedIdentity!.id:crypto.randomUUID(),title:title.trim(),origin,confirmation,project:{schemaVersion:'spatial-v1',scene,profile,scenario},decision,notes});if(same)next.createdAt=savedIdentity!.createdAt;onSave(next);setSavedIdentity({id:next.id,createdAt:next.createdAt,originHash:contentHash(origin)});setPlan(next);setError('');setStatus('Improvement plan saved on this device. No physical work is marked complete.');}catch(e){setError((e as Error).message);}}
  function backup(){if(!plan)return;try{const blob=new Blob([serializePlan(plan)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mercature-plan-${plan.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Local backup downloaded. Source permissions remain attached; private reports stay local.');}catch(e){setError((e as Error).message);}}
  return <main className="workspace"><header className="workspace-header"><button onClick={onHome}>← Home</button><div><span className="eyebrow">Prepared editing example · Synthetic</span><h1>{scene.title}</h1></div><button className="primary" onClick={save}>Save improvement plan</button></header>
    <div className="workspace-body"><section className="model-column"><div className="model-toolbar"><div className="segmented" aria-label="Workspace view">{(['map','3d','split'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='map'?'Map':v==='3d'?'3D':'Split'}</button>)}</div><div className="segmented" aria-label="Scenario comparison"><button aria-pressed={comparison==='original'} onClick={()=>setComparison('original')}>Original</button><button aria-pressed={comparison==='proposed'} onClick={()=>setComparison('proposed')}>Proposed{scenario.operations.length?' · '+scenario.operations.length:''}</button></div><button disabled={!scenario.operations.length} onClick={()=>{setScenario(undoScenario(scenario));dirty();}}>↶ Undo</button></div>
    <SpatialView scene={displayed} result={result} selectedId={selected} onSelect={setSelected} view={view}/>
    <section className="comparison-card" aria-label="Before and after comparison"><div className="section-heading"><div><span className="eyebrow">Same requirements · Recomputed geometry</span><h2>What changes for the next visit?</h2></div><span className="hypothetical">Hypothetical proposal</span></div><div className="outcomes"><Outcome label="Original" result={baseline.destinations[0]?.status??'unknown'}/><span className="outcome-arrow" aria-hidden="true">→</span><Outcome label="Proposed" result={proposed.destinations[0]?.status??'unknown'}/></div><p>{scene.destinations[0]?.label??'Destination'} from the marked start. {scenario.operations.length?'The baseline remains unchanged.':'No change has been applied yet.'}</p><details><summary>Assessment scope and unresolved checks</summary><p>Envelope-centre assessment area: {baseline.reachableArea.toFixed(2)} m² connected originally; {proposed.reachableArea.toFixed(2)} m² in the proposal. This is not usable floor area or visitor capacity.</p><p>{proposed.unknownArea.toFixed(2)} m² remain unresolved under the proposal. Hidden ground stays unknown.</p><ul>{proposed.unsupported.map(x=><li key={x}>{x}</li>)}{proposed.assumptions.map(x=><li key={x}>{x}</li>)}</ul></details></section>
    <Companion>{confirmation?scenario.operations.length?'The proposal is separate from the original. Compare both, then save what you intend to do.':'Your feature is confirmed. A change can help, have no effect, or create another obstruction.':'Select a feature in the model and inspect its evidence. You make the final association.'}</Companion></section>
    <aside className="workflow-panel"><section className="workflow-step"><span className="eyebrow">Understand the concern</span><h2>What needs a closer look?</h2><div className="segmented issue-modes"><button aria-pressed={mode==='proactive'} onClick={()=>{setMode('proactive');resetReview();}}>Check the site</button><button aria-pressed={mode==='concern'} onClick={()=>{setMode('concern');resetReview();}}>Visitor concern</button></div>{mode==='concern'?<><label>Original visitor message<textarea rows={3} maxLength={4000} value={message} onChange={e=>{setMessage(e.target.value);resetReview();}} placeholder="For example: the bench made the entrance difficult to pass."/></label><label>Message language<select value={language} onChange={e=>{setLanguage(e.target.value);resetReview();}}><option value="en">English</option><option value="ko">한국어 · Korean</option><option value="other">Other / unsure</option></select></label><p className="fine-print">Manual association is available. Local language matching is being evaluated; the message cannot establish dimensions or movability.</p></>:<p>Review the modeled approach under the requirements below. Inspect a known feature and confirm the issue against its evidence.</p>}
    <label>Affected feature<select value={target} onChange={e=>{setTarget(e.target.value);setSelected(e.target.value);resetReview();}}>{inventory.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label><button className="text-button" onClick={()=>{if(selected&&inventory.some(i=>i.id===selected)){setTarget(selected);resetReview();}}} disabled={!selected||!inventory.some(i=>i.id===selected)}>Use selected feature</button><label>Your reviewed interpretation<textarea rows={2} value={interpretation} maxLength={4000} onChange={e=>{setInterpretation(e.target.value);resetReview();}} placeholder="What does the evidence support?"/></label><button className={confirmation?'confirmed-button':'primary'} onClick={confirm}>{confirmation?'✓ Feature confirmed':'Confirm feature and issue'}</button><p className="fine-print">Confirmation links this concern to known evidence. It does not validate measurements.</p></section>
    <section className="workflow-step"><span className="eyebrow">Preview a supported change</span><h2>Make room to pass</h2>{feature?.movable?<><p>{confirmation?'Choose a hypothetical move or removal.':'Confirm the movable bench above to try a change.'}</p><div className="move-fields"><label>New X (m)<input type="number" step="0.1" value={move.x} onChange={e=>setMove({...move,x:e.target.value})}/></label><label>New Y (m)<input type="number" step="0.1" value={move.y} onChange={e=>setMove({...move,y:e.target.value})}/></label></div><div className="edit-buttons"><button disabled={!editable} onClick={()=>{if(!move.x.trim()||!move.y.trim()){setError('Enter both placement coordinates.');return;}edit({kind:'move',objectId:target,to:{x:Number(move.x),y:Number(move.y)}});}}>Preview move</button><button disabled={!editable} onClick={()=>edit({kind:'remove',objectId:target})}>Preview removal</button></div><p className="fine-print">Position is the object's minimum X/Y corner in metres. Placement must fit known support and avoid other objects.</p></>:<p>This feature has no supported move or removal. Keep its evidence available and choose another target or save a review without a physical change.</p>}</section>
    <details className="requirements"><summary>Movement requirements</summary><p>Authored values, not a wheelchair prescription or regulatory standard.</p><div className="move-fields"><label>Square width (m)<input aria-label="Square width in metres" type="number" min="0.1" max="3" step="0.1" value={profile.width} onChange={e=>changeProfile({...profile,width:Number(e.target.value)})}/></label><label>Headroom (m)<input aria-label="Headroom in metres" type="number" min="0.1" max="4" step="0.1" value={profile.height} onChange={e=>changeProfile({...profile,height:Number(e.target.value)})}/></label></div><p>Horizontal support and fixed-axis translations only. Required unsupported checks keep the outcome unresolved.</p>{(['turning','longitudinalSlope','crossSlope','multilevel'] as const).map(k=><label className="check-row" key={k}><input type="checkbox" checked={profile.requirements[k]} onChange={e=>changeProfile({...profile,requirements:{...profile.requirements,[k]:e.target.checked}})}/>{({turning:'Turning',longitudinalSlope:'Slope',crossSlope:'Cross-slope',multilevel:'Movement between levels'})[k]} required (unsupported)</label>)}</details>
    <section className="workflow-step plan-fields"><span className="eyebrow">Save the decision</span><h2>Your improvement plan</h2><label>Plan title<input value={title} maxLength={160} onChange={e=>{setTitle(e.target.value);dirty();}}/></label><label>Decision<select value={decision} onChange={e=>{setDecision(e.target.value as ImprovementPlan['decision']);dirty();}}><option value="planned">Proposed</option><option value="approved">Approved for action</option><option value="rejected">Rejected</option></select></label><label>Next actions and unresolved questions<textarea rows={3} value={notes} maxLength={4000} onChange={e=>{setNotes(e.target.value);dirty();}} placeholder="What needs checking on site before acting?"/></label><button className="primary" disabled={!confirmation} onClick={save}>Save improvement plan</button><button disabled={!plan} onClick={backup}>Download local backup</button><p className="fine-print">Saving or approving does not mark physical work complete. Local backups retain private-source restrictions.</p></section></aside></div>
    <div className="workspace-notices" aria-live="polite">{error&&<p role="alert" className="error-text">{error}</p>}{status&&<p role="status">{status}</p>}</div></main>;
}
function Outcome({label,result}:{label:string;result:string}){return <div className={`outcome outcome-${result}`}><span>{label}</span><strong>{result==='reachable'?'Connected':result==='blocked'?'Blocked':'Unresolved'}</strong></div>;}
